### ISSUE TITLE
注册失败，图片上传失败

### ISSUE THREAD

**Issue by Aewait** [Lrunlin/blog#4]
注册`https://blogweb.cn/`    的时候，点邮箱里面的链接出现了这个报错，是因为什么呢？

![x2NvjO.png](https://s1.ax1x.com/2022/10/24/x2NvjO.png)

**Comment by Lrunlin** [comment]
这里是因为服务器根据用户ID的hash生成头像图片上传，后进行注册，应该是七牛OSS那里配置的问题，我排查一下

**Comment by Lrunlin** [comment]
在修改ID生成规则以及变量名时候漏掉了这个模块，导致返回了一个函数，图片名称出现了错误，[本次上传已修复](https://github.com/Lrunlin/blog/commit/ba96d4b437960f2ff96fb3435fd565847d33a7f1)

**Comment by Lrunlin** [comment]
感谢提醒

**Comment by Lrunlin** [comment]
生产环境已重启，可以再尝试一下,感兴趣的话git clone

**Comment by Aewait** [comment]
> 生产环境已重启，可以再尝试一下,感兴趣的话git clone

好的👌
