### ISSUE TITLE
server目录下env问题(环境变量问题解答)

### ISSUE THREAD

**Issue by unfetteredman2020** [Lrunlin/blog#5]
两个问题：
1，入口index里面配置dotenv，看引入路径是引入的其实是根目录下的.env文件，但其实master上面根目录没有这个文件；
2，script里面dev下的index，为什么要read 一下env目录下的env.template文件，最后又去write进原文件？

**Comment by Lrunlin** [comment]
启动之后会把.env和.env.dev合并成一个env文件放到dist里面，然后index去读取.env

**Comment by unfetteredman2020** [comment]
> 启动之后会把.env和.env.dev合并成一个env文件放到dist里面，然后index去读取.env

那第二个问题呢？

**Comment by Lrunlin** [comment]
兑取env.template文件是写入，对于dev是去读，因为防止把一些密钥上传到github上面，每次运行都会生成一个env.template文件用来修改成对应开发环境的环境变量，具体可以查看readme中的环境变量
![image](https://user-images.githubusercontent.com/54397964/199450180-e2288d89-e3fa-4993-a5cf-37d40cf0b37c.png)

**Comment by unfetteredman2020** [comment]
> 

了解，但是还是有个疑问点，index里面引入的.env ，根目录下是没有的，这个怎么解释？

**Comment by Lrunlin** [comment]
因为TSC的速度非常慢，所以项目其实使用了增量编译，在启动时tsc在开发时增量编译TS文件
![image](https://user-images.githubusercontent.com/54397964/199451130-a0a24484-858a-4532-8fbc-78b3ccc32dd2.png)

总的来说其实node.js运行的dist下的文件，在项目启动时TSC后自动吧env文件(.env、.env.dev)移动合并至dist
![image](https://user-images.githubusercontent.com/54397964/199451243-9f8f0e10-17b6-4d7e-8dac-44f51d59089e.png)

**Comment by Lrunlin** [comment]
因为server中涉及到七牛云的key，所以才使用了这个方法，有空的话可能会使用git hook来解决

**Comment by unfetteredman2020** [comment]
> > 
> 
> 了解，但是还是有个疑问点，index里面引入的.env ，根目录下是没有的，这个怎么解释？

看到你的截图我就知道了，master上你没有上传.env 文件，感谢您的答疑解惑

**Comment by Lrunlin** [comment]
没事的，感兴趣的话可以点个star

**Comment by unfetteredman2020** [comment]
哈哈，没问题
