### ISSUE TITLE
server启动报错，望解惑

### ISSUE THREAD

**Issue by walkerxin** [Lrunlin/blog#6]
MySQL安装，.env.template也加上了DB信息，但是yarn dev 时报错（下图）
![image](https://user-images.githubusercontent.com/44486634/216914978-ac676954-9d23-41c4-bf53-5cce7c8883f3.png)

**Comment by Lrunlin** [comment]
`.env.template`只是模板正式使用时候需要最少复制出来一个`.env.development`来作为生产环境的环境变量。详情见Readme,md中的环境变量内容。

![image](https://user-images.githubusercontent.com/54397964/216926673-19447fd4-cf7e-41e3-b002-6e8b0db39ef8.png)

**Comment by Lrunlin** [comment]
如果这个方法无效，请将具体的问题发给我。谢谢
